name: Oburix CI.

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    # Lint for shell scripts.
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
